SELECT
	b.B1_APP_TYPE_ALIAS recType
	,b.B1_ALT_ID recordNbr
	,b3.B1_ALT_ID parentRecNbr
	,b.B1_APPL_STATUS_DATE statDate
	,b.B1_APPL_STATUS applStat
	,g3s.GA_FNAME||' '||g3s.GA_LNAME asgnStaf
	,contct.contName applNam
	,b.B1_SPECIAL_TEXT projectNam
	,NVL(TO_CHAR(b3aV.B1_HSE_NBR_START),'')
	||NVL(NULLIF(' '||TRIM(b3aV.B1_STR_DIR),' '),'')
	||NVL(NULLIF(' '||TRIM(b3aV.B1_STR_NAME),' '),'')
	||NVL(NULLIF(' '||TRIM(b3aV.B1_STR_SUFFIX),' '),'')
	||NVL(NULLIF(' '||TRIM(b3aV.B1_UNIT_TYPE),' '),'')
	||NVL(NULLIF(' '||TRIM(b3aV.B1_UNIT_START),' '),'') addr
	,b3pV.B1_PARCEL_NBR parcelNbr
	,(
		SELECT
			LISTAGG(b2.B1_ALT_ID,', ') WITHIN GROUP (ORDER BY b2.B1_ALT_ID)
		FROM B1PERMIT b2
		INNER JOIN XAPP2REF xa ON
			xa.SERV_PROV_CODE = b2.SERV_PROV_CODE
			AND xa.B1_PER_ID1 = b2.B1_PER_ID1
			AND xa.B1_PER_ID2 = b2.B1_PER_ID2
			AND xa.B1_PER_ID3 = b2.B1_PER_ID3
			AND xa.REC_STATUS = b2.REC_STATUS
		WHERE
			2=2
			AND b3.SERV_PROV_CODE = xa.SERV_PROV_CODE
			AND b3.B1_PER_ID1 = xa.B1_MASTER_ID1
			AND b3.B1_PER_ID2 = xa.B1_MASTER_ID2
			AND b3.B1_PER_ID3 = xa.B1_MASTER_ID3
			AND b3.REC_STATUS = xa.REC_STATUS
			AND b2.B1_PER_GROUP = 'Planning'
			AND b2.B1_PER_TYPE = 'Master Case'
			AND NOT b2.B1_PER_SUB_TYPE = 'Master Case'
			AND b2.B1_PER_CATEGORY = 'NA'
			AND NOT b2.B1_ALT_ID = b.B1_ALT_ID
		) childRecs
FROM B1PERMIT b
LEFT OUTER JOIN BPERMIT_DETAIL bpd ON
	b.SERV_PROV_CODE = bpd.SERV_PROV_CODE
	AND b.B1_PER_ID1 = bpd.B1_PER_ID1
	AND b.B1_PER_ID2 = bpd.B1_PER_ID2
	AND b.B1_PER_ID3 = bpd.B1_PER_ID3
	AND b.REC_STATUS = bpd.REC_STATUS
	LEFT OUTER JOIN G3STAFFS g3s ON
		bpd.SERV_PROV_CODE = g3s.SERV_PROV_CODE
		AND bpd.REC_STATUS = g3s.REC_STATUS
		AND bpd.B1_ASGN_STAFF = g3s.GA_USER_ID
LEFT OUTER JOIN XAPP2REF xa2 ON
	b.SERV_PROV_CODE = xa2.SERV_PROV_CODE
	AND b.B1_PER_ID1 = xa2.B1_PER_ID1
	AND b.B1_PER_ID2 = xa2.B1_PER_ID2
	AND b.B1_PER_ID3 = xa2.B1_PER_ID3
	AND b.REC_STATUS = xa2.REC_STATUS
	LEFT OUTER JOIN B1PERMIT b3 ON
		xa2.SERV_PROV_CODE = b3.SERV_PROV_CODE
		AND xa2.B1_MASTER_ID1 = b3.B1_PER_ID1
		AND xa2.B1_MASTER_ID2 = b3.B1_PER_ID2
		AND xa2.B1_MASTER_ID3 = b3.B1_PER_ID3
		AND xa2.REC_STATUS = b3.REC_STATUS
		AND b2.B1_PER_GROUP = 'Planning'
		AND b2.B1_PER_TYPE = 'Master Case'
		AND b2.B1_PER_SUB_TYPE = 'Master Case'
		AND b2.B1_PER_CATEGORY = 'NA'
LEFT OUTER JOIN(
	SELECT
		b3c.SERV_PROV_CODE
		,b3c.B1_PER_ID1
		,b3c.B1_PER_ID2
		,b3c.B1_PER_ID3
		,b3c.B1_BUSINESS_NAME contBus
		,COALESCE(b3c.B1_FULL_NAME,b3c.B1_FNAME||' '||b3c.B1_LNAME) contName
		,b3c.B1_ADDRESS1 contAddr1
		,CASE WHEN NOT b3c.B1_ADDRESS2 IS NULL THEN b3c.B1_ADDRESS2
			ELSE b3c.B1_CITY||', '||b3c.B1_STATE||' '||b3c.B1_ZIP
				END AS contAddr2
		,CASE WHEN b3c.B1_ADDRESS2 IS NULL THEN NULL
			WHEN NOT b3c.B1_ADDRESS2 IS NULL AND NOT b3c.B1_ADDRESS3 IS NULL
				THEN b3c.B1_ADDRESS3
			WHEN NOT b3c.B1_ADDRESS2 IS NULL AND b3c.B1_ADDRESS3 IS NULL
				THEN b3c.B1_CITY||', '||b3c.B1_STATE||' '||b3c.B1_ZIP
			WHEN b3c.B1_ADDRESS2 IS NULL AND b3c.B1_ADDRESS3 IS NULL THEN NULL
				END AS contAddr3	
		,CASE WHEN NOT b3c.B1_ADDRESS3 IS NULL
			THEN b3c.B1_CITY||', '||b3c.B1_STATE||' '||b3c.B1_ZIP
				ELSE NULL END AS contAddr4
		,b3c.B1_PHONE1 contHmPhn
		,b3c.B1_PHONE2 contMobPhn
		,b3c.B1_PHONE3 contBusPhn
		,b3c.B1_FAX contFax
		,b3c.B1_EMAIL contEmail
	FROM B3CONTACT b3c
	WHERE
		1=1
		AND b3c.SERV_PROV_CODE = 'SANTACLARITA'
		AND b3c.REC_STATUS = 'A'
		AND b3c.B1_CONTACT_TYPE = 'Applicant' --SPECIFY CONTACT TYPE
		AND b3c.B1_CONTACT_NBR = (
			SELECT
				MIN(b3cS.B1_CONTACT_NBR)
			FROM B3CONTACT b3cS
			WHERE
				2=2
				AND b3cS.SERV_PROV_CODE = b3c.SERV_PROV_CODE
				AND b3cS.B1_PER_ID1 = b3c.B1_PER_ID1
				AND b3cS.B1_PER_ID2 = b3c.B1_PER_ID2
				AND b3cS.B1_PER_ID3 = b3c.B1_PER_ID3
				AND b3cS.REC_STATUS = b3c.REC_STATUS
				AND b3cS.B1_CONTACT_TYPE = 'Applicant'
				AND COALESCE(b3cS.B1_FLAG,'N') = (
					SELECT
						MAX(COALESCE(b3cS2.B1_FLAG,'N'))
					FROM B3CONTACT b3cS2
					WHERE
						3=3
						AND b3cS2.SERV_PROV_CODE = b3cS.SERV_PROV_CODE
						AND b3cS2.B1_PER_ID1 = b3cS.B1_PER_ID1
						AND b3cS2.B1_PER_ID2 = b3cS.B1_PER_ID2
						AND b3cS2.B1_PER_ID3 = b3cS.B1_PER_ID3
						AND b3cS2.REC_STATUS = b3cS.REC_STATUS
						AND b3cS2.B1_CONTACT_TYPE = 'Applicant'
					)
				)
	) contct ON
	b.SERV_PROV_CODE = contct.SERV_PROV_CODE
	AND b.B1_PER_ID1 = contct.B1_PER_ID1
	AND b.B1_PER_ID2 = contct.B1_PER_ID2
	AND b.B1_PER_ID3 = contct.B1_PER_ID3
LEFT OUTER JOIN (
	SELECT
		b3p.SERV_PROV_CODE
		,b3p.B1_PER_ID1
		,b3p.B1_PER_ID2
		,b3p.B1_PER_ID3
		,b3p.B1_LEGAL_DESC
		,b3p.B1_PARCEL_NBR
	FROM B3PARCEL b3p
	WHERE
		2=2
		AND b3p.SERV_PROV_CODE = 'SANTACLARITA'
		AND b3p.REC_STATUS = 'A'
		AND b3p.B1_PARCEL_NBR = (
		SELECT
			MIN(b3pS.B1_PARCEL_NBR)
		FROM B3PARCEL b3pS
		WHERE
			3=3
			AND b3pS.SERV_PROV_CODE = b3p.SERV_PROV_CODE
			AND b3pS.B1_PER_ID1 = b3p.B1_PER_ID1
			AND b3pS.B1_PER_ID2 = b3p.B1_PER_ID2
			AND b3pS.B1_PER_ID3 = b3p.B1_PER_ID3
			AND b3pS.REC_STATUS = b3p.REC_STATUS
			AND COALESCE(b3pS.B1_PRIMARY_PAR_FLG,'N') = (
				SELECT
					MAX(COALESCE(b3pS2.B1_PRIMARY_PAR_FLG,'N'))
				FROM B3PARCEL b3pS2
				WHERE
					4=4
					AND b3pS2.SERV_PROV_CODE = b3pS.SERV_PROV_CODE
					AND b3pS2.B1_PER_ID1 = b3pS.B1_PER_ID1
					AND b3pS2.B1_PER_ID2 = b3pS.B1_PER_ID2
					AND b3pS2.B1_PER_ID3 = b3pS.B1_PER_ID3
					AND b3pS2.REC_STATUS = b3pS.REC_STATUS
				)
			)
		) b3pV ON
	b.SERV_PROV_CODE = b3pV.SERV_PROV_CODE
	AND b.B1_PER_ID1 = b3pV.B1_PER_ID1
	AND b.B1_PER_ID2 = b3pV.B1_PER_ID2
	AND b.B1_PER_ID3 = b3pV.B1_PER_ID3		
LEFT OUTER JOIN (
	SELECT
		b3a.SERV_PROV_CODE
		,b3a.B1_PER_ID1
		,b3a.B1_PER_ID2
		,b3a.B1_PER_ID3
		,b3a.B1_HSE_NBR_START
		,b3a.B1_STR_DIR
		,b3a.B1_STR_NAME
		,b3a.B1_STR_SUFFIX
		,b3a.B1_UNIT_START
		,b3a.B1_UNIT_TYPE
		,b3a.B1_SITUS_CITY
		,b3a.B1_SITUS_STATE
		,b3a.B1_SITUS_ZIP
	FROM B3ADDRES b3a
	WHERE
		2=2
		AND b3a.SERV_PROV_CODE = 'SANTACLARITA'
		AND b3a.REC_STATUS = 'A'
		AND b3a.B1_ADDRESS_NBR = (
			SELECT
				MIN(b3aS.B1_ADDRESS_NBR)
			FROM B3ADDRES b3aS
			WHERE
				3=3
				AND b3aS.SERV_PROV_CODE = b3a.SERV_PROV_CODE
				AND b3aS.B1_PER_ID1 = b3a.B1_PER_ID1
				AND b3aS.B1_PER_ID2 = b3a.B1_PER_ID2
				AND b3aS.B1_PER_ID3 = b3a.B1_PER_ID3
				AND b3aS.REC_STATUS = b3a.REC_STATUS
				AND COALESCE(b3aS.B1_PRIMARY_ADDR_FLG,'N') = (
					SELECT
						MAX(COALESCE(b3aS2.B1_PRIMARY_ADDR_FLG,'N'))
					FROM B3ADDRES b3aS2
					WHERE
						4=4
						AND b3aS2.SERV_PROV_CODE = b3aS.SERV_PROV_CODE
						AND b3aS2.B1_PER_ID1 = b3aS.B1_PER_ID1
						AND b3aS2.B1_PER_ID2 = b3aS.B1_PER_ID2
						AND b3aS2.B1_PER_ID3 = b3aS.B1_PER_ID3
						AND b3aS2.REC_STATUS = b3aS.REC_STATUS
				)
			)
		) b3aV ON
	b.SERV_PROV_CODE = b3aV.SERV_PROV_CODE
	AND b.B1_PER_ID1 = b3aV.B1_PER_ID1
	AND b.B1_PER_ID2 = b3aV.B1_PER_ID2
	AND b.B1_PER_ID3 = b3aV.B1_PER_ID3
WHERE
	1=1
	AND b.SERV_PROV_CODE = 'SANTACLARITA'
	AND b.REC_STATUS = 'A'
	AND b.B1_PER_GROUP = 'Planning'
	AND b.B1_PER_TYPE = 'Master Case'
	AND b.B1_PER_SUB_TYPE = '{?entitlement}'
	AND b.B1_PER_CATEGORY = 'NA'
	AND (
			b.B1_APPL_STATUS_DATE >= {?startDate}
			AND b.B1_APPL_STATUS_DATE <= {?endDate}
			)		