SELECT
	b.B1_SPECIAL_TEXT projNam
	,g3s.GA_FNAME||' '||g3s.GA_LNAME userNam
	,'Traffic '||SUBSTR(f4f.GF_DES,1,(INSTR(f4f.GF_DES,'-',1,1)-2))||' Fees' feeGrp1
	,SUBSTR(f4f.GF_DES,(INSTR(f4f.GF_DES,'-',1,1)+2),LENGTH(f4f.GF_DES)) feeGrp2
	,f4f.GF_UNIT feeQty
	,f4f.GF_UDES unitDesc
	,(f4f.GF_FEE/f4f.GF_UNIT) feeEach
	,f4f.GF_FEE fee
FROM B1PERMIT b
LEFT OUTER JOIN G3STAFFS g3s ON
	b.SERV_PROV_CODE = g3s.SERV_PROV_CODE
	AND b.REC_STATUS = g3s.REC_STATUS
	AND g3s.GA_USER_ID = '{?userId}'
INNER JOIN F4FEEITEM f4f ON
	b.SERV_PROV_CODE = f4f.SERV_PROV_CODE
	AND b.B1_PER_ID1 = f4f.B1_PER_ID1
	AND b.B1_PER_ID2 = f4f.B1_PER_ID2
	AND b.B1_PER_ID3 = f4f.B1_PER_ID3
	AND b.REC_STATUS = f4f.REC_STATUS
	AND f4f.GF_ITEM_STATUS_FLAG = 'INVOICED'
WHERE
	1=1
	AND b.SERV_PROV_CODE = 'SANTACLARITA'
	AND b.REC_STATUS = 'A'
	AND b.B1_PER_GROUP = 'Traffic'
	AND b.B1_PER_SUB_TYPE = 'NA'
	AND b.B1_PER_CATEGORY = 'NA'
	AND b.B1_SPECIAL_TEXT = '{?projNam}'
