SELECT
	NVL(TO_CHAR(b3aV.B1_HSE_NBR_START),'')
	||NVL(NULLIF(' '||TRIM(b3aV.B1_STR_DIR),' '),'')
	||NVL(NULLIF(' '||TRIM(b3aV.B1_STR_NAME),' '),'')
	||NVL(NULLIF(' '||TRIM(b3aV.B1_STR_SUFFIX),' '),'')
	||NVL(NULLIF(' '||TRIM(b3aV.B1_UNIT_TYPE),' '),'')
	||NVL(NULLIF(' '||TRIM(b3aV.B1_UNIT_START),' '),'') addr
	,b.B1_SPECIAL_TEXT projectNam
	,bwd.B1_WORK_DESC descOfWork
	,ownr.ownerName ownr
	,cont.fullName applcnt
	,eng.B1_BUS_NAME enginr
	,dev.B1_BUS_NAME devlpr
	,contra.B1_BUS_NAME ocBusnam
	,contra.B1_LICENSE_NBR oclicNbr
	,CASE NVL(tsiV.ownrBldr,'UNCHECKED')
		WHEN 'UNCHECKED' THEN contra.addr1
		WHEN 'CHECKED' THEN ownr.Addr1 END AS ocAddr1
	,CASE NVL(tsiV.ownrBldr,'UNCHECKED')
		WHEN 'UNCHECKED' THEN contra.addr2
		WHEN 'CHECKED' THEN ownr.Addr2 END AS ocAddr2
	,CASE NVL(tsiV.ownrBldr,'UNCHECKED')
		WHEN 'UNCHECKED' THEN contra.city
		WHEN 'CHECKED' THEN ownr.city END AS ocCity
	,CASE NVL(tsiV.ownrBldr,'UNCHECKED')
		WHEN 'UNCHECKED' THEN contra.state
		WHEN 'CHECKED' THEN ownr.state END AS ocState
	,CASE NVL(tsiV.ownrBldr,'UNCHECKED')
		WHEN 'UNCHECKED' THEN contra.zip
		WHEN 'CHECKED' THEN ownr.zip END AS ocZip	
	,CASE NVL(tsiV.ownrBldr,'UNCHECKED')
		WHEN 'UNCHECKED' THEN contra.B1_PHONE1
		WHEN 'CHECKED' THEN ownr.phone END AS ocPhon
	,g3atrV.wcCoNam wcNam
	,g3atrV.wcPolicyNbr wcPolNbr
	,b.B1_ALT_ID permitNbr
	,gp.GA_FNAME||' '||gp.GA_LNAME issuedBy
	,gp.G6_STAT_DD issueDate
	,DECODE(NVL(bc.B1_CHECKLIST_COMMENT,'N'),'N','No','Y','Yes','No') AS soilsReq
	,tsiV.emerContNam AS emrgCont
	,tsiV.emerContPhn AS emrgContPhon
	,gp.G6_STAT_DD + 180 expirDate
	,b.B1_PER_ID1
	,b.B1_PER_ID2
	,b.B1_PER_ID3
FROM B1PERMIT b
LEFT OUTER JOIN BWORKDES bwd ON
	b.SERV_PROV_CODE = bwd.SERV_PROV_CODE
	AND b.B1_PER_ID1 = bwd.B1_PER_ID1
	AND b.B1_PER_ID2 = bwd.B1_PER_ID2
	AND b.B1_PER_ID3 = bwd.B1_PER_ID3
	AND b.REC_STATUS = bwd.REC_STATUS
LEFT OUTER JOIN B3CONTRA eng ON
	b.SERV_PROV_CODE = eng.SERV_PROV_CODE
	AND b.B1_PER_ID1 = eng.B1_PER_ID1
	AND b.B1_PER_ID2 = eng.B1_PER_ID2
	AND b.B1_PER_ID3 = eng.B1_PER_ID3
	AND b.REC_STATUS = eng.REC_STATUS
	AND eng.B1_LICENSE_TYPE = 'Engineer'
LEFT OUTER JOIN B3CONTRA dev ON
	b.SERV_PROV_CODE = dev.SERV_PROV_CODE
	AND b.B1_PER_ID1 = dev.B1_PER_ID1
	AND b.B1_PER_ID2 = dev.B1_PER_ID2
	AND b.B1_PER_ID3 = dev.B1_PER_ID3
	AND b.REC_STATUS = dev.REC_STATUS
	AND dev.B1_LICENSE_TYPE = 'Developer'
LEFT OUTER JOIN BCHCKBOX bc ON
	b.SERV_PROV_CODE = bc.SERV_PROV_CODE
	AND b.B1_PER_ID1 = bc.B1_PER_ID1	
	AND b.B1_PER_ID2 = bc.B1_PER_ID2
	AND b.B1_PER_ID3 = bc.B1_PER_ID3
	AND b.REC_STATUS = bc.REC_STATUS
	AND bc.B1_CHECKBOX_TYPE = 'PROJECT INFORMATION'
	AND bc.B1_CHECKBOX_DESC= 'Soils/Geotechnical Report Required'
LEFT OUTER JOIN (
	SELECT
		b3lp.SERV_PROV_CODE
		,b3lp.B1_PER_ID1
		,b3lp.B1_PER_ID2
		,b3lp.B1_PER_ID3
		,b3lp.B1_LICENSE_NBR
		,b3lp.B1_LICENSE_TYPE
		,b3lp.B1_LIC_EXPIR_DD
		,b3lp.B1_BUS_NAME
		,b3lp.B1_CAE_FNAME
		,b3lp.B1_CAE_LNAME
		,b3lp.B1_ADDRESS1 addr1
		,b3lp.B1_ADDRESS2 addr2
		,b3lp.B1_CITY city
		,b3lp.B1_STATE state
		,b3lp.B1_ZIP zip
		ELSE NULL END AS addr4
		,b3lp.B1_PHONE1
		,b3lp.B1_PHONE2
		,b3lp.B1_FAX
		,b3lp.B1_EMAIL
		,rsl.LIC_SEQ_NBR
	FROM B3CONTRA b3lp
	INNER JOIN RSTATE_LIC rsl ON
		b3lp.SERV_PROV_CODE = rsl.SERV_PROV_CODE
		AND b3lp.REC_STATUS = rsl.REC_STATUS
		AND b3lp.B1_LICENSE_TYPE = rsl.LIC_TYPE
		AND b3lp.B1_LICENSE_NBR = rsl.LIC_NBR
	WHERE
		2=2
		AND b3lp.SERV_PROV_CODE = 'SANTACLARITA'
		AND b3lp.REC_STATUS = 'A'
		AND b3lp.B1_LICENSE_TYPE = 'Contractor'
		AND b3lp.B1_LICENSE_NBR = (
			SELECT
				MIN(b3lpS.B1_LICENSE_NBR)
			FROM B3CONTRA b3lpS
			WHERE
				2=2
				AND b3lpS.SERV_PROV_CODE = b3lp.SERV_PROV_CODE
				AND b3lpS.B1_PER_ID1 = b3lp.B1_PER_ID1
				AND b3lpS.B1_PER_ID2 = b3lp.B1_PER_ID2
				AND b3lpS.B1_PER_ID3 = b3lp.B1_PER_ID3
				AND b3lpS.REC_STATUS = b3lp.REC_STATUS
				AND b3lpS.B1_LICENSE_TYPE = 'Contractor'
				AND COALESCE(b3lpS.B1_PRINT_FLAG,'N') = (
					SELECT
						MAX(COALESCE(b3lpS2.B1_PRINT_FLAG,'N'))
					FROM B3CONTRA b3lpS2
					WHERE
						3=3
						AND b3lpS2.SERV_PROV_CODE = b3lpS.SERV_PROV_CODE
						AND b3lpS2.B1_PER_ID1 = b3lpS.B1_PER_ID1
						AND b3lpS2.B1_PER_ID2 = b3lpS.B1_PER_ID2
						AND b3lpS2.B1_PER_ID3 = b3lpS.B1_PER_ID3
						AND b3lpS2.REC_STATUS = b3lpS.REC_STATUS
						AND b3lpS2.B1_LICENSE_TYPE = 'Contractor'
					)
				)
			) contra ON
	b.SERV_PROV_CODE = contra.SERV_PROV_CODE
	AND b.B1_PER_ID1 = contra.B1_PER_ID1
	AND b.B1_PER_ID2 = contra.B1_PER_ID2
	AND b.B1_PER_ID3 = contra.B1_PER_ID3
	LEFT OUTER JOIN (
		SELECT
			g3atr.SERV_PROV_CODE
			,g3atr.G1_CONTACT_NBR
			,g3atr.G1_ATTRIBUTE_NAME
			,g3atr.G1_ATTRIBUTE_VALUE
		FROM G3CONTACT_ATTRIBUTE g3atr
		WHERE
			2=2
			AND g3atr.SERV_PROV_CODE = 'SANTACLARITA'
			AND g3atr.REC_STATUS = 'A'
			AND g3atr.G1_CONTACT_TYPE = 'Contractor'
			AND g3atr.G1_ATTRIBUTE_NAME IN ('WC CO NAME','WC POLICY NO')
			) a
	PIVOT(
		MAX(G1_ATTRIBUTE_VALUE)
		FOR G1_ATTRIBUTE_NAME IN ('WC CO NAME' AS wcCoNam,'WC POLICY NO' AS wcPolicyNbr)
		) g3atrV ON
		contra.SERV_PROV_CODE = g3atrV.SERV_PROV_CODE
		AND contra.LIC_SEQ_NBR = g3atrV.G1_CONTACT_NBR	
LEFT OUTER JOIN (
	SELECT
		b4.SERV_PROV_CODE
		,b4.B1_PER_ID1
		,b4.B1_PER_ID2
		,b4.B1_PER_ID3
		,b3cC.B1_FNAME fName
		,b3cC.B1_MNAME mName
		,b3cC.B1_LNAME lName
		,COALESCE(b3cC.B1_FULL_NAME,(b3cC.B1_FNAME||' '||b3cC.B1_LNAME)) fullName
		,b3cC.B1_BUSINESS_NAME busName
		,b3cC.B1_PHONE1 hmPhone
		,b3cC.B1_PHONE2	mobPhone
		,b3cC.B1_PHONE3 busPhone
		,b3cC.B1_EMAIL email
	FROM B1PERMIT b4
	INNER JOIN B3CONTACT b3cC ON
		b4.SERV_PROV_CODE = b3cC.SERV_PROV_CODE
		AND b4.B1_PER_ID1 = b3cC.B1_PER_ID1
		AND b4.B1_PER_ID2 = b3cC.B1_PER_ID2
		AND b4.B1_PER_ID3 = b3cC.B1_PER_ID3
		AND b4.REC_STATUS = b3cC.REC_STATUS
	WHERE
		2=2
		AND b4.SERV_PROV_CODE = 'SANTACLARITA'
		AND b4.REC_STATUS = 'A'
		AND b4.B1_ALT_ID = '{?altId}'
		AND b3cC.B1_CONTACT_TYPE = 'Applicant'
		AND b3cC.B1_CONTACT_NBR = (
			SELECT
				MAX(b3cCS.B1_CONTACT_NBR)
			FROM B3CONTACT b3cCS
			WHERE
				3=3
				AND b3cCS.SERV_PROV_CODE = b3cC.SERV_PROV_CODE
				AND b3cCS.B1_PER_ID1 = b3cC.B1_PER_ID1
				AND b3cCS.B1_PER_ID2 = b3cC.B1_PER_ID2
				AND b3cCS.B1_PER_ID3 = b3cC.B1_PER_ID3
				AND b3cCS.REC_STATUS = b3cC.REC_STATUS
				AND b3cCS.B1_CONTACT_TYPE = 'Applicant' 
				AND COALESCE(b3cCS.B1_FLAG,'N') = ( 
					SELECT
						MAX(COALESCE(b3cCS2.B1_FLAG,'N'))
					FROM B3CONTACT b3cCS2
					WHERE
						4=4
						AND b3cCS2.SERV_PROV_CODE = b3cCS.SERV_PROV_CODE
						AND b3cCS2.B1_PER_ID1 = b3cCS.B1_PER_ID1
						AND b3cCS2.B1_PER_ID2 = b3cCS.B1_PER_ID2
						AND b3cCS2.B1_PER_ID3 = b3cCS.B1_PER_ID3
						AND b3cCS2.REC_STATUS = b3cCS.REC_STATUS
						AND b3cCS2.B1_CONTACT_TYPE = 'Applicant' 
					)					
				)
		) cont ON
	b.SERV_PROV_CODE = cont.SERV_PROV_CODE
	AND b.B1_PER_ID1 = cont.B1_PER_ID1
	AND b.B1_PER_ID2 = cont.B1_PER_ID2
	AND b.B1_PER_ID3 = cont.B1_PER_ID3
LEFT OUTER JOIN (
	SELECT
		b5.SERV_PROV_CODE
		,b5.B1_PER_ID1
		,b5.B1_PER_ID2
		,b5.B1_PER_ID3
		,COALESCE(b3o.B1_OWNER_FULL_NAME,b3o.B1_OWNER_FNAME||' '||b3o.B1_OWNER_LNAME) ownerName
		,b3o.B1_MAIL_ADDRESS1 addr1
		,b3o.B1_MAIL_ADDRESS2 addr2
		,b3o.B1_MAIL_CITY city
		,b3o.B1_MAIL_STATE state
		,b3o.B1_MAIL_ZIP zip
		,COALESCE(b3o.B1_PHONE,'No Phone') phone
		,b3o.B1_EMAIL email
	FROM B1PERMIT b5
	INNER JOIN B3OWNERS b3o ON
		b5.SERV_PROV_CODE = b3o.SERV_PROV_CODE
		AND b5.B1_PER_ID1 = b3o.B1_PER_ID1
		AND b5.B1_PER_ID2 = b3o.B1_PER_ID2
		AND b5.B1_PER_ID3 = b3o.B1_PER_ID3
		AND b5.REC_STATUS = b3o.REC_STATUS
	WHERE
		2=2
		AND b5.SERV_PROV_CODE = 'SANTACLARITA'
		AND b5.REC_STATUS = 'A'
		AND b5.B1_ALT_ID = '{?altId}'
		AND b3o.B1_OWNER_NBR = (
			SELECT
				MIN(b3oS.B1_OWNER_NBR)
			FROM B3OWNERS b3oS
			WHERE
				3=3
				AND b3oS.SERV_PROV_CODE = b3o.SERV_PROV_CODE
				AND b3oS.B1_PER_ID1 = b3o.B1_PER_ID1
				AND b3oS.B1_PER_ID2 = b3o.B1_PER_ID2
				AND b3oS.B1_PER_ID3 = b3o.B1_PER_ID3
				AND b3oS.REC_STATUS = b3o.REC_STATUS
				AND COALESCE(b3oS.B1_PRIMARY_OWNER,'N') = (
					SELECT
						MAX(COALESCE(b3oS2.B1_PRIMARY_OWNER,'N'))
					FROM B3OWNERS b3oS2
					WHERE
						4=4
						AND b3oS2.SERV_PROV_CODE = b3oS.SERV_PROV_CODE
						AND b3oS2.B1_PER_ID1 = b3oS.B1_PER_ID1
						AND b3oS2.B1_PER_ID2 = b3oS.B1_PER_ID2
						AND b3oS2.B1_PER_ID3 = b3oS.B1_PER_ID3
						AND b3oS2.REC_STATUS = b3oS.REC_STATUS
					)
				)
	) ownr ON
	b.SERV_PROV_CODE = ownr.SERV_PROV_CODE
	AND b.B1_PER_ID1 = ownr.B1_PER_ID1
	AND b.B1_PER_ID2 = ownr.B1_PER_ID2
	AND b.B1_PER_ID3 = ownr.B1_PER_ID3
	
--B3ADDRES (RECORD ADDRESS)
LEFT OUTER JOIN (
	SELECT
		b3a.SERV_PROV_CODE
		,b3a.B1_PER_ID1
		,b3a.B1_PER_ID2
		,b3a.B1_PER_ID3
		,b3a.B1_HSE_NBR_START
		,b3a.B1_STR_DIR
		,b3a.B1_STR_NAME
		,b3a.B1_STR_SUFFIX
		,b3a.B1_UNIT_START
		,b3a.B1_UNIT_TYPE
		,b3a.B1_SITUS_CITY
		,b3a.B1_SITUS_STATE
		,b3a.B1_SITUS_ZIP
	FROM B3ADDRES b3a
	WHERE
		2=2
		AND b3a.SERV_PROV_CODE = 'SANTACLARITA'
		AND b3a.REC_STATUS = 'A'
		AND b3a.B1_ADDRESS_NBR = (
			SELECT
				MIN(b3aS.B1_ADDRESS_NBR)
			FROM B3ADDRES b3aS
			WHERE
				3=3
				AND b3aS.SERV_PROV_CODE = b3a.SERV_PROV_CODE
				AND b3aS.B1_PER_ID1 = b3a.B1_PER_ID1
				AND b3aS.B1_PER_ID2 = b3a.B1_PER_ID2
				AND b3aS.B1_PER_ID3 = b3a.B1_PER_ID3
				AND b3aS.REC_STATUS = b3a.REC_STATUS
				AND COALESCE(b3aS.B1_PRIMARY_ADDR_FLG,'N') = (
					SELECT
						MAX(COALESCE(b3aS2.B1_PRIMARY_ADDR_FLG,'N'))
					FROM B3ADDRES b3aS2
					WHERE
						4=4
						AND b3aS2.SERV_PROV_CODE = b3aS.SERV_PROV_CODE
						AND b3aS2.B1_PER_ID1 = b3aS.B1_PER_ID1
						AND b3aS2.B1_PER_ID2 = b3aS.B1_PER_ID2
						AND b3aS2.B1_PER_ID3 = b3aS.B1_PER_ID3
						AND b3aS2.REC_STATUS = b3aS.REC_STATUS
				)
			)
		) b3aV ON
	b.SERV_PROV_CODE = b3aV.SERV_PROV_CODE
	AND b.B1_PER_ID1 = b3aV.B1_PER_ID1
	AND b.B1_PER_ID2 = b3aV.B1_PER_ID2
	AND b.B1_PER_ID3 = b3aV.B1_PER_ID3 
LEFT OUTER JOIN GPROCESS gp ON
	b.SERV_PROV_CODE = gp.SERV_PROV_CODE
	AND b.B1_PER_ID1 = gp.B1_PER_ID1
	AND b.B1_PER_ID2 = gp.B1_PER_ID2
	AND b.B1_PER_ID3 = gp.B1_PER_ID3
	AND b.REC_STATUS = gp.REC_STATUS
	AND gp.SD_PRO_DES = 'Permit Issuance'
	AND gp.SD_APP_DES = 'Issued'
LEFT OUTER JOIN (
	SELECT
		tsi.SERV_PROV_CODE
		,tsi.B1_PER_ID1
		,tsi.B1_PER_ID2
		,tsi.B1_PER_ID3
		,tsi.B1_CHECKBOX_TYPE
		,tsi.B1_CHECKBOX_DESC
		,tsi.B1_CHECKLIST_COMMENT
	FROM GPROCESS_SPEC_INFO tsi
	WHERE
		2=2
		AND tsi.SERV_PROV_CODE = 'SANTACLARITA'
		AND tsi.REC_STATUS = 'A'
		AND tsi.B1_CHECKBOX_TYPE = 'DS_GRDPERMIT'
		AND tsi.B1_CHECKBOX_DESC IN ('Owner/Builder?','24-hour Contact Name'
				,'24-hour Contact Phone')
	) t
PIVOT(
		MAX(B1_CHECKLIST_COMMENT)
		FOR B1_CHECKBOX_DESC IN ('Owner/Builder?' AS ownrBldr,'24-hour Contact Name' AS emerContNam
				,'24-hour Contact Phone' AS emerContPhn)
) tsiV ON
	b.SERV_PROV_CODE = tsiV.SERV_PROV_CODE
	AND b.B1_PER_ID1 = tsiV.B1_PER_ID1
	AND b.B1_PER_ID2 = tsiV.B1_PER_ID2
	AND b.B1_PER_ID3 = tsiV.B1_PER_ID3
WHERE
	1=1
	AND b.SERV_PROV_CODE = 'SANTACLARITA'
	AND b.REC_STATUS = 'A'
	AND b.B1_PER_GROUP = 'Eng_Services'
	AND b.B1_PER_TYPE = 'Grading and Associated Plans'
	AND b.B1_PER_SUB_TYPE = 'Grading'
	AND b.B1_PER_CATEGORY = 'NA'
	AND b.B1_ALT_ID = '{?altId}'