SELECT
	COALESCE(cont.busName,cont.contName) developer
	,b.B1_ALT_ID recordNbr
	,aat1.GF_L1 feeAccount
	,aat1.TRAN_AMOUNT - NVL(aat2.pmts,0) amtDue
FROM B1PERMIT b
LEFT OUTER JOIN (
	SELECT
		b4.SERV_PROV_CODE
		,b4.B1_PER_ID1
		,b4.B1_PER_ID2
		,b4.B1_PER_ID3
		,b3cC.B1_FNAME||' '||b3cC.B1_LNAME contName
		,b3cC.B1_BUSINESS_NAME busName
	FROM B1PERMIT b4
	INNER JOIN B3CONTACT b3cC ON
		b4.SERV_PROV_CODE = b3cC.SERV_PROV_CODE
		AND b4.B1_PER_ID1 = b3cC.B1_PER_ID1
		AND b4.B1_PER_ID2 = b3cC.B1_PER_ID2
		AND b4.B1_PER_ID3 = b3cC.B1_PER_ID3
		AND b4.REC_STATUS = b3cC.REC_STATUS
	WHERE
		2=2
		AND b4.SERV_PROV_CODE = 'SANTACLARITA'
		AND b4.REC_STATUS = 'A'
		AND b3cC.B1_CONTACT_TYPE = 'Developer'
		AND b3cC.B1_CONTACT_NBR = (
			SELECT
				MAX(b3cCS.B1_CONTACT_NBR)
			FROM B3CONTACT b3cCS
			WHERE
				3=3
				AND b3cCS.SERV_PROV_CODE = b3cC.SERV_PROV_CODE
				AND b3cCS.B1_PER_ID1 = b3cC.B1_PER_ID1
				AND b3cCS.B1_PER_ID2 = b3cC.B1_PER_ID2
				AND b3cCS.B1_PER_ID3 = b3cC.B1_PER_ID3
				AND b3cCS.REC_STATUS = b3cC.REC_STATUS
				AND b3cCS.B1_CONTACT_TYPE = 'Developer' 
				AND COALESCE(b3cCS.B1_FLAG,'N') = ( 
					SELECT
						MAX(COALESCE(b3cCS2.B1_FLAG,'N'))
					FROM B3CONTACT b3cCS2
					WHERE
						4=4
						AND b3cCS2.SERV_PROV_CODE = b3cCS.SERV_PROV_CODE
						AND b3cCS2.B1_PER_ID1 = b3cCS.B1_PER_ID1
						AND b3cCS2.B1_PER_ID2 = b3cCS.B1_PER_ID2
						AND b3cCS2.B1_PER_ID3 = b3cCS.B1_PER_ID3
						AND b3cCS2.REC_STATUS = b3cCS.REC_STATUS
						AND b3cCS2.B1_CONTACT_TYPE = 'Developer' 
					)					
				)
		) cont ON
	b.SERV_PROV_CODE = cont.SERV_PROV_CODE
	AND b.B1_PER_ID1 = cont.B1_PER_ID1
	AND b.B1_PER_ID2 = cont.B1_PER_ID2
	AND b.B1_PER_ID3 = cont.B1_PER_ID3
LEFT OUTER JOIN ACCELA.ACCOUNTING_AUDIT_TRAIL aat1 ON
	b.SERV_PROV_CODE = aat1.SERV_PROV_CODE
	AND b.B1_PER_ID1 = aat1.B1_PER_ID1
	AND b.B1_PER_ID2 = aat1.B1_PER_ID2
	AND b.B1_PER_ID3 = aat1.B1_PER_ID3
	AND b.REC_STATUS = aat1.REC_STATUS
	AND aat1.ACTION = 'Invoice FeeItem'
	LEFT OUTER JOIN (
			SELECT
				aatX.SERV_PROV_CODE
				,aatX.B1_PER_ID1
				,aatX.B1_PER_ID2
				,aatX.B1_PER_ID3
				,aatX.FEEITEM_SEQ_NBR
				,SUM(aatX.TRAN_AMOUNT) pmts
			FROM ACCELA.ACCOUNTING_AUDIT_TRAIL aatX
			WHERE
				2=2
				AND aatX.SERV_PROV_CODE = 'SANTACLARITA'
				AND aatX.REC_STATUS = 'A'
				AND aatX.ACTION IN ('Payment Applied','Void Payment Applied','Refund Applied')
			GROUP BY
				aatX.SERV_PROV_CODE
				,aatX.B1_PER_ID1
				,aatX.B1_PER_ID2
				,aatX.B1_PER_ID3
				,aatX.FEEITEM_SEQ_NBR	
	)aat2 ON
		aat1.SERV_PROV_CODE = aat2.SERV_PROV_CODE
		AND aat1.B1_PER_ID1 = aat2.B1_PER_ID1
		AND aat1.B1_PER_ID2 = aat2.B1_PER_ID2
		AND aat1.B1_PER_ID3 = aat2.B1_PER_ID3
		AND aat1.FEEITEM_SEQ_NBR = aat2.FEEITEM_SEQ_NBR
WHERE
	1=1
	AND b.SERV_PROV_CODE = 'SANTACLARITA'
	AND b.REC_STATUS = 'A'
	AND b.B1_PER_GROUP = 'Eng_Services'
	AND (aat1.TRAN_AMOUNT - NVL(aat2.pmts,0)) > 0