SELECT
	b6c.B1_CON_LONG_COMMENT
FROM B6CONDIT b6c
WHERE
	1=1
	AND b6c.SERV_PROV_CODE = 'SANTACLARITA'
	AND b6c.REC_STATUS = 'A'
	AND b6c.B1_PER_ID1 = '{?perId1}'
	AND b6c.B1_PER_ID2 = '{?perId2}'
	AND b6c.B1_PER_ID3 = '{?perId3}'
	AND NVL(b6c.COND_APRV_FLAG,'N') = 'N' 